stds.bizhawklibs = {
  "bit",
  "client",
  "console",
  "emu",
  "event",
  "forms",
  "gameinfo",
  "gui",
  "input",
  "joypad",
  "memory",
  "userdata"
}
stds.trackerglobals = {
  "Battle",
  "ColorPicker",
  "Constants",
  "Drawing",
  "GameSettings",
  "Inifile",
  "Input",
  "Main",
  "Memory",
  "Options",
  "Pickle",
  "Program",
  "Theme",
  "Tracker",
  "Utils",
  "AbilityData",
  "MiscData",
  "MoveData",
  "RouteData",
  "PokemonData",
  "SpainData",
  "ItalyData",
  "FranceData",
  "GermanyData",
  "NavigationMenu",
  "GameOptionsScreen",
  "InfoScreen",
  "QuickloadScreen",
  "SetupScreen",
  "StartupScreen",
  "TrackerScreen",
  "TrackedDataScreen",
  "AddItems",
  "Debug",
  "Symbols",
}
std.otherglobals = {"love"}
std = "lua51c+bizhawklibs+trackerglobals+otherglobals"
ignore = {"631"}
