name: Luacheck
on:
  push:
    branches-ignore: ['fellshadow/main']
    paths: '**.lua'
  
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1.0.0
